name: data-engine

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run data engine
        run: python -m scripts.engine.data_engine --config config/data_engine.yaml
      - name: Commit and push results
        env:
          TZ: Etc/UTC
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --ff-only
          git add out/market out/presets out/portfolios out/diagnostics data/order_history || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git commit -m "chore(data-engine): update snapshots ${timestamp}"
          git push
